apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-admission-mutation
webhooks:
- name: pods.webhook-admission-mutation.svc.cluster.local
  clientConfig:
    service:
      namespace: anasinnyk
      name: webhook-admission-mutation
      path: /pods
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5akNDQWQ2Z0F3SUJBZ0lRWnp5RkVlTndBUlYxTWxxOXg5ZktIakFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFERXdwemRtTXRZMkYwTFdOaE1CNFhEVEU1TURVd05qRTBNVEUxTTFvWERUSTVNRFV3TXpFMApNVEUxTTFvd0ZURVRNQkVHQTFVRUF4TUtjM1pqTFdOaGRDMWpZVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTWRDZmQzeHZ3SnpVaWdvOG9UWDlLdlRXVUJNb3ZDRlUyRUExZm9yT2hNeWVDaXkKRit4V3I2UlltV3dicXh2SnRnRGlSSkxmT2UvZGJvSkNWK2F6Qm40Q1dCdXh6R0V0ZWczVUNYS0t0ZEFiSk0xaQpEejFZNGZQenRSMk9sVWp0WGYwdHJGV1pZTThwSWdidkVEWXZSQ2ZFTnNuTlozd3dpZ1ZnZ2NqZFM0YWYzanVjCm5Jb2kwb3FuK3pNOHFXazZWSzI5cXNUaUlPSmxZbU1sUUViamVNZmZuOVpzVFduell0dmNYOHFBNWcxK0IrSncKQWoxeSt1VnhWSDFMMng5bDN3Q1RzcEZmZ0V4OHZqeUlDcVAxL3ZoTGFEYXF2RkVCV1ZKbzZTMjRsa0ZNWWNpSAppWFhETGs2SkJyU2ZDemI3QVNQdHd2K292MmxXYm8xTWxPYXdwc1VDQXdFQUFhTkNNRUF3RGdZRFZSMFBBUUgvCkJBUURBZ0trTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3JCZ0VGQlFjREFqQVBCZ05WSFJNQkFmOEUKQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJjbCtCRXdiUWR0cHhyYm0yMDRrakVUM2Y4R3JNWgpUY1lodHVkUE45WWdtb0tLSjl3UHFFS3MrM0NyZWQ3em5PL3lJeHJnTDBZRmtpaUVFWXA1cExJcGF0d2QwOWNzCnVHU3ROUXM5bUo5d3BvTm5EV3hMM3JFQXJYV1JzUCsyWnFkdU1aS1hHMHFFTnpXdWNBblkySFMyNXRFR29GMTQKeHpXb1VZTXdNenRteXpHbElTQ0NXbS9WOGgzNVEwL2d3T2R6eEtVaHRaQzdWYmpYVktPVS9XTXZicUxGYUhpdApwQ1k1Zk9SRnUxZWdxSVo1cnJpRUFCV2tYb0QzNFh4UEFwUXFvUXVvZHpVQmh1NG1PanBoYTQ5ZWRxSG5HSUFFCnBDK2VRRXM3ZllUWkpaalZMb0hmaHY3SUZmM1JLY3NYWHM2ZzVaNEFWL09KWDFmWXVKM2J0RURmCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:
  - operations:
    - CREATE
    apiGroups:
    - "*"
    apiVersions:
    - "*"
    resources:
    - pods
  failurePolicy: Fail
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values:
      - webhook-admission-mutation
      - kube-system
      - anasinnyk
