apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: webhook-admission-mutation
  name: webhook-admission-mutation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-admission-mutation
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook-admission-mutation
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: webhook-admission-mutation
subjects:
- kind: ServiceAccount
  namespace: webhook-admission-mutation
  name: webhook-admission-mutation