apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-psp
  namespace: anasinnyk
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - 100-default-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-default-psp
  namespace: anasinnyk
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: default
subjects:
- kind: ServiceAccount
  namespace: anasinnyk
  name: deafult
